package nl.rug.oop.rpg;

/**
 * Venom: Regenerates health at the start of each turn.
 */
public class Venom extends Villain {

    private static final long serialVersionUID = 1L;

    /** HP regenerated by the symbiote each round. */
    private static final int REGEN_PER_TURN = 3;

    /**
     * Construct a new Venom.
     *
     * @param difficulty current game difficulty; scales the villain's stats.
     * @param drop       optional item awarded to the player on defeat.
     */
    public Venom(Difficulty difficulty, Item drop) {
        super("Venom",
                "Eddie Brock, wrapped in a writhing black symbiote with too many teeth.",
                70, 9, difficulty, drop);
    }

    /**
     * Heal {@value #REGEN_PER_TURN} HP at the start of each round
     * if not already at full HP and not already dead.
     */
    @Override
    public void onTurnStart() {
        if (getHealth() < getMaxHealth() && !isDead()) {
            heal(REGEN_PER_TURN);
            System.out.println("The symbiote knits itself back together. (Venom +" + REGEN_PER_TURN + " HP)");
        }
    }
}